# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ test ]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Maven Central Repository # Configures settings.xml with required credentials
      uses: actions/setup-java@v4
      with: # The environment variables are defined when needed (here, when the package is being published)
        distribution: 'temurin'
        java-version: '17'
        server-id: 'ossrh' 
        server-username: MAVEN_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Install xmllint
      run: sudo apt-get update && sudo apt-get install -y libxml2-utils

    - name: Determine release list
      run: bash -c ./service_config/version_check.sh

    - name: Check environment variable
      run: |
        echo "List of modules ${{ env.ARTIFACTS_TO_BE_RELEASED }}"

